import { useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowLeft, Printer } from 'lucide-react';

export default function StudentReport() {
  const location = useLocation();
  const navigate = useNavigate();

  // The modal passes the selected filtered students and selected fields via React Router state
  const { students = [], fields = [] } = location.state || {};

  useEffect(() => {
    // If someone ends up here directly without state, send them back
    if (!location.state) {
      navigate('/dashboard');
    }
  }, [location, navigate]);

  if (!location.state) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="min-h-screen bg-gray-100 font-sans">
      {/* Non-printable Action Bar */}
      <div className="bg-white border-b border-gray-200 px-8 py-4 flex items-center justify-between sticky top-0 print:hidden z-10 shadow-sm">
        <button 
          onClick={() => navigate(-1)} 
          className="flex items-center gap-2 text-sm font-bold text-gray-500 hover:text-gray-900 border border-gray-200 px-4 py-2 rounded-xl"
        >
          <ArrowLeft className="w-4 h-4" /> Back to Directory
        </button>
        <button 
          onClick={handlePrint}
          className="flex items-center gap-2 bg-indigo-600 text-white text-sm font-bold px-6 py-2 rounded-xl shadow-lg shadow-indigo-200 hover:bg-indigo-700 active:scale-95 transition-all"
        >
          <Printer className="w-4 h-4" /> Print / Save PDF
        </button>
      </div>

      {/* Printable Document A4 Container */}
      <div className="max-w-[1200px] mx-auto my-8 bg-white shadow-xl print:m-0 print:shadow-none print:max-w-none">
        
        {/* Document Padding */}
        <div className="p-12 print:p-8">
          
          {/* Header */}
          <div className="border-b-[3px] border-gray-900 pb-6 mb-8 flex justify-between items-end">
            <div>
              <h1 className="text-3xl font-black text-gray-900 uppercase tracking-tight">Student Directory Report</h1>
              <p className="text-sm font-medium text-gray-500 mt-2">Official System Export</p>
            </div>
            <div className="text-right text-xs font-bold text-gray-500">
              <p>Generated On: {new Date().toLocaleDateString()}</p>
              <p>Total Records: {students.length}</p>
            </div>
          </div>

          {/* Table */}
          <table className="w-full text-left border-collapse border border-gray-300">
            <thead>
              <tr className="bg-gray-100 print:bg-gray-200">
                <th className="border p-2 text-xs font-bold text-gray-900 uppercase">#</th>
                {fields.map(f => (
                  <th key={f.id} className="border border-gray-300 p-2 text-xs font-bold text-gray-900 uppercase">
                    {f.label}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {students.map((student, idx) => (
                <tr key={student.id} className="even:bg-gray-50/50 print:even:bg-transparent">
                  <td className="border border-gray-300 p-2 text-[0.7rem] font-mono text-gray-500 w-1">
                    {idx + 1}
                  </td>
                  {fields.map(f => {
                    let val = student[f.id];
                    if (f.id === 'phone') val = student.mobile_numbers?.[0] || '—';
                    if (!val) val = '—';
                    return (
                      <td key={f.id} className="border border-gray-300 p-2 text-[0.75rem] text-gray-800 break-words">
                        {val}
                      </td>
                    );
                  })}
                </tr>
              ))}
            </tbody>
          </table>

          {/* Footer */}
          <div className="mt-12 pt-6 border-t border-gray-200 text-center text-[0.65rem] text-gray-400 font-medium pb-8 print:fixed print:bottom-0 print:w-full print:pt-4 print:mt-0 print:border-none">
            Confidential Document — Generated by Students Data Store
          </div>
          
        </div>
      </div>
    </div>
  );
}
