-- NUCLEAR RESET: Manual SQL Schema Build

-- 1. CLEANUP
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;

SET search_path TO public;

-- 2. TABLES
CREATE TABLE users (
    id VARCHAR PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by VARCHAR REFERENCES users(id)
);

CREATE TABLE roles (
    id VARCHAR PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    description TEXT,
    is_system_role BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by VARCHAR REFERENCES users(id)
);

CREATE TABLE user_roles (
    user_id VARCHAR REFERENCES users(id) ON DELETE CASCADE,
    role_id VARCHAR REFERENCES roles(id) ON DELETE CASCADE,
    assigned_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    assigned_by VARCHAR REFERENCES users(id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE permissions (
    id VARCHAR PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    module VARCHAR(50) NOT NULL,
    action VARCHAR(50) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE (module, action)
);

CREATE TABLE role_permissions (
    role_id VARCHAR REFERENCES roles(id) ON DELETE CASCADE,
    permission_id VARCHAR REFERENCES permissions(id) ON DELETE CASCADE,
    granted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    granted_by VARCHAR REFERENCES users(id),
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE students (
    id VARCHAR PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    class_name VARCHAR(50),
    roll_no VARCHAR(50),
    admission_no VARCHAR(50),
    mobile_numbers JSONB,
    address VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    zip_code VARCHAR(20),
    date_of_birth VARCHAR(20),
    enrollment_date TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    notes TEXT,
    submitted_via_form BOOLEAN NOT NULL DEFAULT FALSE,
    form_submission_code VARCHAR(50) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE widgets (
    id VARCHAR PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    description TEXT,
    component_key VARCHAR(100) NOT NULL,
    widget_type VARCHAR(50) NOT NULL,
    default_config JSONB,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE widget_permissions (
    widget_id VARCHAR REFERENCES widgets(id) ON DELETE CASCADE,
    permission_id VARCHAR REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (widget_id, permission_id)
);

CREATE TABLE user_widget_preferences (
    user_id VARCHAR REFERENCES users(id) ON DELETE CASCADE,
    widget_id VARCHAR REFERENCES widgets(id) ON DELETE CASCADE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    position JSONB,
    PRIMARY KEY (user_id, widget_id)
);

CREATE TABLE audit_logs (
    id BIGSERIAL PRIMARY KEY,
    user_id VARCHAR REFERENCES users(id),
    action VARCHAR(100) NOT NULL,
    resource VARCHAR(100),
    resource_id VARCHAR(255),
    details JSONB,
    ip_address VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE form_links (
    id VARCHAR PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    token VARCHAR(50) UNIQUE NOT NULL,
    allowed_fields JSONB NOT NULL DEFAULT '[]',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by VARCHAR REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE form_submissions (
    id VARCHAR PRIMARY KEY,
    form_link_id VARCHAR REFERENCES form_links(id) ON DELETE CASCADE,
    submitted_data JSONB NOT NULL DEFAULT '{}',
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 3. VERSIONING
CREATE TABLE alembic_version (
    version_num VARCHAR(32) PRIMARY KEY
);
INSERT INTO alembic_version VALUES ('0001_initial_fresh_start');

-- 4. SEEDING (Admin Account)
-- Note: Password is 'asdf1234#+' hashed
-- Using the hash generated by the system: $2b$12$K.mREqB8P76G6S8S7S8S7O (dummy hash, I'll update it to real one)
-- Wait, I'll just let the server auto-seed once the tables exist!
