"""Initial schema

Revision ID: 7ba7b029c0ab
Revises: 
Create Date: 2026-04-11 04:33:43.974409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ba7b029c0ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_students_email', table_name='students')
    op.drop_index('ix_students_first_name', table_name='students')
    op.drop_index('ix_students_form_submission_code', table_name='students')
    op.drop_index('ix_students_is_active', table_name='students')
    op.drop_table('students')
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.create_table('students',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('enrollment_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_via_form', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('form_submission_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('class_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('roll_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('admission_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mobile_numbers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='students_pkey')
    )
    op.create_index('ix_students_is_active', 'students', ['is_active'], unique=False)
    op.create_index('ix_students_form_submission_code', 'students', ['form_submission_code'], unique=True)
    op.create_index('ix_students_first_name', 'students', ['first_name'], unique=False)
    op.create_index('ix_students_email', 'students', ['email'], unique=True)
    # ### end Alembic commands ###
